### ISSUE TITLE
Contracts to support solc 0.5.x

### ISSUE THREAD

**Issue by nkuba** [summa-tx/bitcoin-spv#18]
Currently, contracts have fixed pragma to `0.4.25`. It would be super usefull to have the contracts supporting solc `0.5.x`.

I tried to bump the pragma to `>=0.4.25 <0.6.0;` but encountered a few issues, e.g.
```
bitcoin-spv/contracts/BTCUtils.sol:44:33: TypeError: Explicit type conversion not allowed from "bytes1" to "uint256".
            _number = _number + uint(_b[i]) * (2 ** (8 * (_b.length - (i + 1))));

bitcoin-spv/contracts/ValidateSPV.sol:66:41: TypeError: Return arguments required.
        if (!validatePrefix(_prefix)) { return; }
```

**Comment by prestwich** [comment]
The second error is easy. We used a bunch of bare `return;` statements, which in older pragmas are a shortcut for returning `0` cast to the appropriate return type. So for each bare `return;` we need to add an explicit statement casting `0` to the appropriate type

The first error means that the type system has changed in 0.5.0. And that is going to be much more frustrating to figure out a way around. The bytes types are rather poorly documented. 

Specifically the problem is `uint(_b[i])`, which indexes the bytearray and casts the single byte to unsigned integer. This function could probably be written better in assembly
